config/routes.rb
Rails.application.routes.draw do
  resources :buildings do
    resources :apartments
  end
end

app/models/apartment.rb
class Apartment < ApplicationRecord

  belongs_to :building
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord

  has_many :apartments

#Método to_s
  def to_s
      name
  end

end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController

  def index
    @building = Building.find(params[:building_id])
    @apartments = @building.apartments # Se muestran los apartmentsasociados a este building
  end

  def new
    @building = Building.find(params[:building_id])
    @apartment = Apartment.new
  end

  def show
    @building = Building.find(params[:building_id])
    @apartment = Apartment.find(params[:id])
  end

  def edit
    @building = Building.find(params[:building_id])
    @apartment = Apartment.find(params[:id])
  end



  def update
    @building = Building.find params[:building_id]
    @apartment = Apartment.find params[:id]
    respond_to do |format|
      if @apartment.update(apartment_params.merge(building: @building))
          format.html { redirect_to building_apartment_path, notice: 'Apartment was successfully updated.' }
      else
        format.html { render :edit }
    end
  end
end




def destroy
   @apartment = Apartment.find params[:id]
   @apartment.destroy
   respond_to do |format|
     format.html { redirect_to building_apartments_url, notice: 'Apartment was successfully destroyed.' }
end end




  def create
    @building = Building.find params[:building_id]
    @apartment = Apartment.new(apartment_params) #Strong parameters, previene ataques de mass assignment
    @apartment.building = @building #Asignamos el building, ya no esnecesario pasarlo en el formulario, ahora viene en la url
      respond_to do |format|
      if @apartment.save
        format.html { redirect_to building_apartment_path(@building, @apartment), notice: 'Apartment was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

    private

    def apartment_params
      params.require(:apartment).permit(:number)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apartments/_form.html.erb
<%= form_with(model: [@building, apartment], local: true) do |form| %>
<% if apartment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>
    <ul>
      <% apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= form.label :number %>
  <%= form.text_field :number %>
</div>

<div class="actions">
  <%= form.submit %>
</div>


<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>
<%= render 'form', apartment: @apartment %>
<%= link_to 'Show', building_apartment_path(@building, @apartment) %> |
<%= link_to 'Back', building_apartments_path(@building) %>

app/views/apartments/index.html.erb
<h1>Apartments l2</h1>
<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Number</th>
      <th>Building</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.id %></td>
        <td><%= apartment.number %></td>
        <td><%= apartment.building %></td>
        <td><%= link_to 'Mostrar', building_apartment_path(@building, apartment) %></td>
        <td><%= link_to 'Editar', edit_building_apartment_path(@building, apartment) %></td>
        <td><%= link_to 'Destroy', building_apartment_path(@building, apartment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Apartment', new_building_apartment_path(@building) %>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Back', building_apartments_path(@building) %>

app/views/apartments/show.html.erb
<p>
  <strong>Number:</strong>
  <%= @apartment.number %>
</p>
<p>
  <strong>Building:</strong>
  <%= @apartment.building %>
</p>
<%= link_to 'Back', building_apartments_path(@building) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Edificio L2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>